---
name: Git clone
description: Performs a clone of an extra repo in the build step
author: https://github.com/datumforge
requirements: []
configuration:
  properties:
    repository:
      type: string
    branch:
      type: string
  required:
    - repository
  additionalProperties: false